### POST Create a new patient
POST http://localhost:4004/patients
Content-Type: application/json

{
    "name": "Kafka User",
    "email": "kafka@example.com",
    "address": "123 Main St, Springfield, USA",
    "dateOfBirth": "1990-01-01",
    "registeredDate": "2025-05-17"
}
###